### ISSUE TITLE
minor overflow bug

### ISSUE THREAD

**Issue by scandum** [mlochbaum/rhsort#1]
I was checking ./runwolfbench 512 0 0 1 and it crashed on rhsort. Offending code:

```c
      for (; i<n-4; i+=4) { x[i+4] += x[i+3] += x[i+2] += x[i+1] += x[i]; }
      for (; i<n-1; i++) { x[i+1] += x[i]; }
```
Seemingly working fix:
```c
      for (; i+4<n; i+=4) { x[i+4] += x[i+3] += x[i+2] += x[i+1] += x[i]; }
      for (; i+1<n; i++) { x[i+1] += x[i]; }
```

![image](https://user-images.githubusercontent.com/52607428/155850477-2d503d5f-de09-492e-bb2e-fced4ab783c0.png)

Btw, have you had any luck improving performance on the 1-31 range?

**Comment by mlochbaum** [comment]
Thanks. I went for changing `n` because I didn't know if the arithmetic for `i` would lift out of the loop (and didn't think about small numbers) but I don't see a performance difference.

You mean lengths 1 to 31? I think the amount of setup required means short arrays are never viable, so that it would be better to switch to a comparison sort.
